name: untitled
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  shared_preferences: ^2.2.3
  intl: ^0.18.1 # ADDED THIS LINE TO FIX THE BUILD ERROR
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  firebase_storage: ^12.0.1
  share_plus: ^10.1.2
  path_provider: ^2.1.5
  pdf: ^3.11.1
  excel: ^3.0.0
  printing: ^5.13.3
  http: ^1.2.0
  connectivity_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/app_icon.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    # Note: Only include necessary font weights to reduce app size

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#800000"
    theme_color: "#800000"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
